version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - misspell
    - unconvert
    - unparam
    - bodyclose
    - gosec
    - prealloc
    - gocritic
    - revive
  settings:
    errcheck:
      check-type-assertions: false
      check-blank: false
    govet:
      enable:
        - copylocks
    gosec:
      excludes:
        - G304
    revive:
      rules:
        - name: exported
          severity: warning
          disabled: false
        - name: var-naming
          severity: warning
          disabled: false