run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - misspell
    - unconvert
    - unparam
    - bodyclose
    - gosec
    - prealloc
    - gocritic
    - revive
    - gofmt
    - goimports

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  govet:
    check-shadowing: true
  
  gosec:
    excludes:
      - G304  # File inclusion via variable (needed for config files)
  
  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
      - name: var-naming
        severity: warning
        disabled: false

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
    
    # Exclude some linters from running on tests files
    - path: _test\.go
      text: "use of `fmt.Print`"